//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusConnectV2 {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class EN {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EN() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BusConnectV2.EN", typeof(EN).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to a.
        /// </summary>
        internal static string a {
            get {
                return ResourceManager.GetString("a", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to aaaaa.
        /// </summary>
        internal static string aaaaaa {
            get {
                return ResourceManager.GetString("aaaaaa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add point.
        /// </summary>
        internal static string agregar_punto {
            get {
                return ResourceManager.GetString("agregar punto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alerts.
        /// </summary>
        internal static string Avisos {
            get {
                return ResourceManager.GetString("Avisos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expired alerts.
        /// </summary>
        internal static string Avisos_vencidos {
            get {
                return ResourceManager.GetString("Avisos vencidos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current alerts.
        /// </summary>
        internal static string Avisos_vigentes {
            get {
                return ResourceManager.GetString("Avisos vigentes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome.
        /// </summary>
        internal static string Bienvenido {
            get {
                return ResourceManager.GetString("Bienvenido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change photo.
        /// </summary>
        internal static string cambiar_imagen {
            get {
                return ResourceManager.GetString("cambiar imagen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change password.
        /// </summary>
        internal static string Cambias_contraseña {
            get {
                return ResourceManager.GetString("Cambias contraseña", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log out.
        /// </summary>
        internal static string Cerrar_sesion {
            get {
                return ResourceManager.GetString("Cerrar sesion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bus.
        /// </summary>
        internal static string Colectivo {
            get {
                return ResourceManager.GetString("Colectivo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string Configuracion {
            get {
                return ResourceManager.GetString("Configuracion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        internal static string Confirmar {
            get {
                return ResourceManager.GetString("Confirmar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm password.
        /// </summary>
        internal static string Confirmar_contraseña {
            get {
                return ResourceManager.GetString("Confirmar contraseña", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Questions.
        /// </summary>
        internal static string consultas {
            get {
                return ResourceManager.GetString("consultas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string Contraseña {
            get {
                return ResourceManager.GetString("Contraseña", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string Descripcion {
            get {
                return ResourceManager.GetString("Descripcion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit company.
        /// </summary>
        internal static string editar_empresa {
            get {
                return ResourceManager.GetString("editar empresa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit user.
        /// </summary>
        internal static string editar_usuario {
            get {
                return ResourceManager.GetString("editar usuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string Eliminar {
            get {
                return ResourceManager.GetString("Eliminar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete point.
        /// </summary>
        internal static string eliminar_punto {
            get {
                return ResourceManager.GetString("eliminar punto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send.
        /// </summary>
        internal static string Enviar {
            get {
                return ResourceManager.GetString("Enviar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write Question.
        /// </summary>
        internal static string Escribir_consulta {
            get {
                return ResourceManager.GetString("Escribir consulta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End.
        /// </summary>
        internal static string Fin {
            get {
                return ResourceManager.GetString("Fin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate route.
        /// </summary>
        internal static string generar_ruta {
            get {
                return ResourceManager.GetString("generar ruta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save route.
        /// </summary>
        internal static string guardar_ruta {
            get {
                return ResourceManager.GetString("guardar ruta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string Idioma {
            get {
                return ResourceManager.GetString("Idioma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reports.
        /// </summary>
        internal static string informes {
            get {
                return ResourceManager.GetString("informes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log in.
        /// </summary>
        internal static string Ingresar {
            get {
                return ResourceManager.GetString("Ingresar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        internal static string Inicio {
            get {
                return ResourceManager.GetString("Inicio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to lat.
        /// </summary>
        internal static string latitud {
            get {
                return ResourceManager.GetString("latitud", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line.
        /// </summary>
        internal static string Linea {
            get {
                return ResourceManager.GetString("Linea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to long.
        /// </summary>
        internal static string longitud {
            get {
                return ResourceManager.GetString("longitud", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Map.
        /// </summary>
        internal static string Mapa {
            get {
                return ResourceManager.GetString("Mapa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Questions.
        /// </summary>
        internal static string mis_consultas {
            get {
                return ResourceManager.GetString("mis consultas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark Mode.
        /// </summary>
        internal static string Modo_oscuro {
            get {
                return ResourceManager.GetString("Modo oscuro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to                   Name.
        /// </summary>
        internal static string NOMBRE {
            get {
                return ResourceManager.GetString("NOMBRE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question number.
        /// </summary>
        internal static string NroConsulta {
            get {
                return ResourceManager.GetString("NroConsulta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line number.
        /// </summary>
        internal static string nroLinea {
            get {
                return ResourceManager.GetString("nroLinea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        internal static string Perfil {
            get {
                return ResourceManager.GetString("Perfil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Branch.
        /// </summary>
        internal static string Ramal {
            get {
                return ResourceManager.GetString("Ramal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register company.
        /// </summary>
        internal static string Registrar_empresa {
            get {
                return ResourceManager.GetString("Registrar empresa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registrer line.
        /// </summary>
        internal static string Registrar_linea {
            get {
                return ResourceManager.GetString("Registrar linea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register User.
        /// </summary>
        internal static string Registrar_usuario {
            get {
                return ResourceManager.GetString("Registrar usuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        internal static string Registrarse {
            get {
                return ResourceManager.GetString("Registrarse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Response.
        /// </summary>
        internal static string Respuesta {
            get {
                return ResourceManager.GetString("Respuesta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role.
        /// </summary>
        internal static string Rol {
            get {
                return ResourceManager.GetString("Rol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sda.
        /// </summary>
        internal static string sadasd {
            get {
                return ResourceManager.GetString("sadasd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suscriptions.
        /// </summary>
        internal static string suscripciones {
            get {
                return ResourceManager.GetString("suscripciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        internal static string Titulo {
            get {
                return ResourceManager.GetString("Titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        internal static string Usuario {
            get {
                return ResourceManager.GetString("Usuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        internal static string Volver {
            get {
                return ResourceManager.GetString("Volver", resourceCulture);
            }
        }
    }
}
