//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusConnectV2 {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class EN {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EN() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BusConnectV2.EN", typeof(EN).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a a.
        /// </summary>
        internal static string a {
            get {
                return ResourceManager.GetString("a", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Add point.
        /// </summary>
        internal static string agregar_punto {
            get {
                return ResourceManager.GetString("agregar punto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Alerts.
        /// </summary>
        internal static string Avisos {
            get {
                return ResourceManager.GetString("Avisos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Expired alerts.
        /// </summary>
        internal static string Avisos_vencidos {
            get {
                return ResourceManager.GetString("Avisos vencidos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Current alerts.
        /// </summary>
        internal static string Avisos_vigentes {
            get {
                return ResourceManager.GetString("Avisos vigentes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Welcome.
        /// </summary>
        internal static string Bienvenido {
            get {
                return ResourceManager.GetString("Bienvenido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Change photo.
        /// </summary>
        internal static string cambiar_imagen {
            get {
                return ResourceManager.GetString("cambiar imagen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Change password.
        /// </summary>
        internal static string Cambias_contraseña {
            get {
                return ResourceManager.GetString("Cambias contraseña", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Log out.
        /// </summary>
        internal static string Cerrar_sesion {
            get {
                return ResourceManager.GetString("Cerrar sesion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Bus.
        /// </summary>
        internal static string Colectivo {
            get {
                return ResourceManager.GetString("Colectivo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Settings.
        /// </summary>
        internal static string Configuracion {
            get {
                return ResourceManager.GetString("Configuracion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Confirm.
        /// </summary>
        internal static string Confirmar {
            get {
                return ResourceManager.GetString("Confirmar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Confirm password.
        /// </summary>
        internal static string Confirmar_contraseña {
            get {
                return ResourceManager.GetString("Confirmar contraseña", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Questions.
        /// </summary>
        internal static string consultas {
            get {
                return ResourceManager.GetString("consultas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Password.
        /// </summary>
        internal static string Contraseña {
            get {
                return ResourceManager.GetString("Contraseña", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Description.
        /// </summary>
        internal static string Descripcion {
            get {
                return ResourceManager.GetString("Descripcion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Delete.
        /// </summary>
        internal static string Eliminar {
            get {
                return ResourceManager.GetString("Eliminar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Delete point.
        /// </summary>
        internal static string eliminar_punto {
            get {
                return ResourceManager.GetString("eliminar punto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Send.
        /// </summary>
        internal static string Enviar {
            get {
                return ResourceManager.GetString("Enviar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Write Question.
        /// </summary>
        internal static string Escribir_consulta {
            get {
                return ResourceManager.GetString("Escribir consulta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a End.
        /// </summary>
        internal static string Fin {
            get {
                return ResourceManager.GetString("Fin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Generate route.
        /// </summary>
        internal static string generar_ruta {
            get {
                return ResourceManager.GetString("generar ruta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Save route.
        /// </summary>
        internal static string guardar_ruta {
            get {
                return ResourceManager.GetString("guardar ruta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Language.
        /// </summary>
        internal static string Idioma {
            get {
                return ResourceManager.GetString("Idioma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Log in.
        /// </summary>
        internal static string Ingresar {
            get {
                return ResourceManager.GetString("Ingresar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Start.
        /// </summary>
        internal static string Inicio {
            get {
                return ResourceManager.GetString("Inicio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a lat.
        /// </summary>
        internal static string latitud {
            get {
                return ResourceManager.GetString("latitud", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Line.
        /// </summary>
        internal static string Linea {
            get {
                return ResourceManager.GetString("Linea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a long.
        /// </summary>
        internal static string longitud {
            get {
                return ResourceManager.GetString("longitud", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Map.
        /// </summary>
        internal static string Mapa {
            get {
                return ResourceManager.GetString("Mapa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a My Questions.
        /// </summary>
        internal static string mis_consultas {
            get {
                return ResourceManager.GetString("mis consultas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Dark Mode.
        /// </summary>
        internal static string Modo_oscuro {
            get {
                return ResourceManager.GetString("Modo oscuro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a                   Name.
        /// </summary>
        internal static string NOMBRE {
            get {
                return ResourceManager.GetString("NOMBRE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Question number.
        /// </summary>
        internal static string NroConsulta {
            get {
                return ResourceManager.GetString("NroConsulta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Line number.
        /// </summary>
        internal static string nroLinea {
            get {
                return ResourceManager.GetString("nroLinea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Profile.
        /// </summary>
        internal static string Perfil {
            get {
                return ResourceManager.GetString("Perfil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Branch.
        /// </summary>
        internal static string Ramal {
            get {
                return ResourceManager.GetString("Ramal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Register company.
        /// </summary>
        internal static string Registrar_empresa {
            get {
                return ResourceManager.GetString("Registrar empresa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Registrer line.
        /// </summary>
        internal static string Registrar_linea {
            get {
                return ResourceManager.GetString("Registrar linea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Register User.
        /// </summary>
        internal static string Registrar_usuario {
            get {
                return ResourceManager.GetString("Registrar usuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Register.
        /// </summary>
        internal static string Registrarse {
            get {
                return ResourceManager.GetString("Registrarse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Response.
        /// </summary>
        internal static string Respuesta {
            get {
                return ResourceManager.GetString("Respuesta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Role.
        /// </summary>
        internal static string Rol {
            get {
                return ResourceManager.GetString("Rol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a sda.
        /// </summary>
        internal static string sadasd {
            get {
                return ResourceManager.GetString("sadasd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Suscriptions.
        /// </summary>
        internal static string suscripciones {
            get {
                return ResourceManager.GetString("suscripciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Title.
        /// </summary>
        internal static string Titulo {
            get {
                return ResourceManager.GetString("Titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a User.
        /// </summary>
        internal static string Usuario {
            get {
                return ResourceManager.GetString("Usuario", resourceCulture);
            }
        }
    }
}
